#! /bin/sh

# Start up processes

# sxhkd

pgrep -x sxhkd > /dev/null || sxhkd &

# Auto-CPUFreq
#sudo /usr/bin/auto-cpufreq --live &

# Picom
picom -fb --experimental-backends --backend glx &

# Background Wallpaper
nitrogen --restore &

# Network Applet
nm-applet --indicator &

# Bluetooth Applet
blueman-applet &

# Notifications
kilall dunst &
/usr/bin/dunst &

# Polybar
kilall polybar &

polybar top -c ~/.config/polybar/config.ini &
polybar bottom -c ~/.config/polybar/config.ini &

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width         2
bspc config window_gap          10

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#8ab7e8"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a xdman-Main state=floating
bspc rule -a feh state=floating
bspc rule -a davinci-resolve desktop='^8' state=floating follow=on
bspc rule -a galculator state=floating 

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
